
import __ASTRO_IMAGE_IMPORT_ZYOK8c from "./lain.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum.md";
import __ASTRO_IMAGE_IMPORT_ZpRc0 from "./avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome.md";
import __ASTRO_IMAGE_IMPORT_Z2bc1dc from "banner1.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FEmail-Based-User-Enumeration.md";
import __ASTRO_IMAGE_IMPORT_PPlq from "./assets/chaofan-tweet.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
import __ASTRO_IMAGE_IMPORT_Z2089Os from "./assets/sourcemap-r2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
import __ASTRO_IMAGE_IMPORT_Z13oHPr from "./assets/npmimage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
import __ASTRO_IMAGE_IMPORT_pdPqR from "./assets/undercover-ts.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
import __ASTRO_IMAGE_IMPORT_wB8ia from "./assets/buddy-terminal.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
import __ASTRO_IMAGE_IMPORT_2fLnt2 from "./banner2.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md";
export default new Map([["./lain.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Faddendum.md", __ASTRO_IMAGE_IMPORT_ZYOK8c], ["./avatar.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhome.md", __ASTRO_IMAGE_IMPORT_ZpRc0], ["banner1.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2FEmail-Based-User-Enumeration.md", __ASTRO_IMAGE_IMPORT_Z2bc1dc], ["./assets/chaofan-tweet.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_PPlq], ["./assets/sourcemap-r2.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_Z2089Os], ["./assets/npmimage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_Z13oHPr], ["./assets/undercover-ts.png?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_pdPqR], ["./assets/buddy-terminal.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_wB8ia], ["./banner2.gif?astroContentImageFlag=&importer=src%2Fcontent%2Fposts%2Fclaude-code-leak-blog.md", __ASTRO_IMAGE_IMPORT_2fLnt2]]);
		